/**
 * GENERATED by scripts/build-content.js — do not edit by hand.
 * The data-driven category catalog: one entry per distinct lesson
 * `category`. `icon` reuses the category's intro-lesson hero illustration
 * (rendered as the category/row visual); colors come from a fixed palette.
 * Single source of truth for category slugs, titles, colors and visuals.
 */
import type { ImageKey } from "@/constants/images";

export type Category = {
  slug: string;
  /** Frontmatter category label, e.g. "Money & Finance". */
  title: string;
  /** Category hero illustration, reused as the small tile/row visual. */
  icon: ImageKey;
  tint: string;
  bg: string;
  lessonCount: number;
  /** Coin price to unlock; omitted = free. */
  coinCost?: number;
};

export const CATEGORIES: Category[] = [
  { slug: "animals-wildlife", title: "Animals & Wildlife", icon: "animalsEvolutionHero", tint: "#22C55E", bg: "#16321F", lessonCount: 11 },
  { slug: "baking-desserts", title: "Baking & Desserts", icon: "bakingScienceHero", tint: "#FF7A00", bg: "#33230F", lessonCount: 10 },
  { slug: "business-entrepreneurship", title: "Business & Entrepreneurship", icon: "businessIdeaHero", tint: "#4D8BFF", bg: "#15233D", lessonCount: 11 },
  { slug: "career-work", title: "Career & Work", icon: "cvPurposeHero", tint: "#FFB020", bg: "#33290F", lessonCount: 30 },
  { slug: "coding-programming", title: "Coding & Programming", icon: "codingWhatCodeHero", tint: "#2EC4B6", bg: "#16322F", lessonCount: 12 },
  { slug: "communication-people-skills", title: "Communication & People Skills", icon: "bodyLanguageBasicsHero", tint: "#FF4D4F", bg: "#321616", lessonCount: 30 },
  { slug: "cooking-food", title: "Cooking & Food", icon: "coffeeTeaWorldHero", tint: "#B07CFF", bg: "#241A38", lessonCount: 30 },
  { slug: "creative-writing", title: "Creative Writing", icon: "findingVoiceHero", tint: "#FF6FB5", bg: "#331826", lessonCount: 10 },
  { slug: "design-visual-creativity", title: "Design & Visual Creativity", icon: "designPrinciplesHero", tint: "#38BDF8", bg: "#102A38", lessonCount: 10 },
  { slug: "earth-science-geology", title: "Earth Science & Geology", icon: "mountainsFormHero", tint: "#A3E635", bg: "#20300F", lessonCount: 11 },
  { slug: "energy-power", title: "Energy & Power", icon: "energyFossilFuelsHero", tint: "#818CF8", bg: "#1B1F3A", lessonCount: 10 },
  { slug: "everyday-economics", title: "Everyday Economics", icon: "econGdpWhatItIsHero", tint: "#FB7185", bg: "#331519", lessonCount: 30 },
  { slug: "everyday-science", title: "Everyday Science", icon: "biologyLifeHero", tint: "#34D399", bg: "#123024", lessonCount: 30 },
  { slug: "filmmaking-video", title: "Filmmaking & Video", icon: "filmHowMoviesMadeHero", tint: "#F59E0B", bg: "#2E2410", lessonCount: 10 },
  { slug: "future-tech-innovation", title: "Future Tech & Innovation", icon: "futuretechRoboticsHero", tint: "#A78BFA", bg: "#241B3A", lessonCount: 10 },
  { slug: "government-politics", title: "Government & Politics", icon: "govtHowGovernmentWorksHero", tint: "#E879F9", bg: "#2E1633", lessonCount: 11 },
  { slug: "health-body", title: "Health & Body", icon: "bodySystemsHero", tint: "#22C55E", bg: "#16321F", lessonCount: 36 },
  { slug: "history-the-world", title: "History & the World", icon: "countryBasicsHero", tint: "#FF7A00", bg: "#33230F", lessonCount: 25 },
  { slug: "home-car", title: "Home & Car", icon: "carMaintenanceHero", tint: "#4D8BFF", bg: "#15233D", lessonCount: 30 },
  { slug: "how-things-work", title: "How Things Work", icon: "howworksPlanesHero", tint: "#FFB020", bg: "#33290F", lessonCount: 11 },
  { slug: "human-body-deep-dive", title: "Human Body Deep Dive", icon: "brainHowItWorksHero", tint: "#2EC4B6", bg: "#16322F", lessonCount: 11 },
  { slug: "languages-linguistics", title: "Languages & Linguistics", icon: "langHowLanguageWorksHero", tint: "#FF4D4F", bg: "#321616", lessonCount: 10 },
  { slug: "law-your-rights", title: "Law & Your Rights", icon: "lawLegalSystemHero", tint: "#B07CFF", bg: "#241A38", lessonCount: 10 },
  { slug: "logic-critical-thinking", title: "Logic & Critical Thinking", icon: "logicFallaciesHero", tint: "#FF6FB5", bg: "#331826", lessonCount: 10 },
  { slug: "marketing-branding", title: "Marketing & Branding", icon: "marketingWhatItIsHero", tint: "#38BDF8", bg: "#102A38", lessonCount: 10 },
  { slug: "math-concepts", title: "Math Concepts", icon: "mathAlgebraHero", tint: "#A3E635", bg: "#20300F", lessonCount: 10 },
  { slug: "medicine-public-health", title: "Medicine & Public Health", icon: "medicineVaccinesHero", tint: "#818CF8", bg: "#1B1F3A", lessonCount: 10 },
  { slug: "mindfulness", title: "Mindfulness & Mental Wellbeing", icon: "mindfulnessHero", tint: "#2EC4B6", bg: "#16322F", lessonCount: 10 },
  { slug: "money", title: "Money & Finance", icon: "bankHero", tint: "#22C55E", bg: "#16321F", lessonCount: 48 },
  { slug: "music-audio", title: "Music & Audio", icon: "musicHowMusicWorksHero", tint: "#FB7185", bg: "#331519", lessonCount: 10 },
  { slug: "numbers-data-literacy", title: "Numbers & Data Literacy", icon: "dataChartsWhyTheyMatterHero", tint: "#34D399", bg: "#123024", lessonCount: 25 },
  { slug: "parenting-child-development", title: "Parenting & Child Development", icon: "parentingHowChildrenDevelopHero", tint: "#F59E0B", bg: "#2E2410", lessonCount: 10 },
  { slug: "philosophy-big-ideas", title: "Philosophy & Big Ideas", icon: "philosophyWhatItIsHero", tint: "#A78BFA", bg: "#241B3A", lessonCount: 11 },
  { slug: "practical-life-admin", title: "Practical Life Admin", icon: "newUsedHero", tint: "#E879F9", bg: "#2E1633", lessonCount: 30 },
  { slug: "productivity-self-growth", title: "Productivity & Self-Growth", icon: "growthFocusUnderstandingAttentionHero", tint: "#22C55E", bg: "#16321F", lessonCount: 30 },
  { slug: "psychology-mind", title: "Psychology & Mind", icon: "cognitiveBiasHero", tint: "#FF7A00", bg: "#33230F", lessonCount: 25 },
  { slug: "real-estate-property", title: "Real Estate & Property", icon: "realestatePropertyValueHero", tint: "#4D8BFF", bg: "#15233D", lessonCount: 10 },
  { slug: "relationships-dating", title: "Relationships & Dating", icon: "healthyRelationshipsHero", tint: "#FFB020", bg: "#33290F", lessonCount: 10 },
  { slug: "space-deep-dive", title: "Space Deep Dive", icon: "spaceddPlanetsHero", tint: "#2EC4B6", bg: "#16322F", lessonCount: 11 },
  { slug: "sports-fitness", title: "Sports & Fitness", icon: "fitnessHowMusclesGrowHero", tint: "#FF4D4F", bg: "#321616", lessonCount: 10 },
  { slug: "sustainable-living", title: "Sustainable Living", icon: "sustainReducingWasteHero", tint: "#B07CFF", bg: "#241A38", lessonCount: 11 },
  { slug: "technology-online-safety", title: "Technology & Online Safety", icon: "aiPatternFinderHero", tint: "#FF6FB5", bg: "#331826", lessonCount: 30 },
  { slug: "world-cuisines", title: "World Cuisines", icon: "cuisineItalianHero", tint: "#38BDF8", bg: "#102A38", lessonCount: 10 },
  { slug: "world-religions-belief", title: "World Religions & Belief", icon: "religionComparativeOverviewHero", tint: "#A3E635", bg: "#20300F", lessonCount: 10 },
];

/** Data-driven category slug (all slugs are derived from the content). */
export type CategorySlug = string;

/** Per-slug accent colors — drop-in for the old hand-written `categoryColors`. */
export const categoryColors: Record<string, { tint: string; bg: string }> =
  Object.fromEntries(CATEGORIES.map((c) => [c.slug, { tint: c.tint, bg: c.bg }]));

const BY_SLUG = new Map(CATEGORIES.map((c) => [c.slug, c]));
const BY_LABEL = new Map(CATEGORIES.map((c) => [c.title, c]));

/** Lookup a category by slug. */
export function categoryBySlug(slug: string): Category | undefined {
  return BY_SLUG.get(slug);
}

/** Map a frontmatter `category` label to its slug (undefined if unknown). */
export function slugForLabel(label: string): string | undefined {
  return BY_LABEL.get(label)?.slug;
}
